name: frontend:review

on:
  pull_request:
    types: [reopened, opened, synchronize, edited]

jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Check lint
        run: cross-env eslint 'src/**/*.{ts,tsx,stories.tsx}' --quiet
      - name: Check formatting
        run: cross-env prettier --check 'src/**/*.{ts,tsx,stories.tsx}'
      - name: Check type-check
        run: tsc --noEmit

  build:
    needs: static-check
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Generate build
        run: npm run build
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Deploy to firebase
        id: firebase-deploy
        uses: mohammed-atif/firebase-publish-react@v1.0
        with:
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}
      - name: Verify Output
        run: echo ${{ steps.firebase-deploy.outputs.hosting-url }}
