name: frontend:demo

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'demo/**'

jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: echo DEMO