name: deploy:prod

on:
  push:
    tags:
      - "**"
jobs:
  deployProd:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set variables
        id: step1
        run: |
          Branch=${GITHUB_REF/refs\/tags\//}
          echo $Branch
          if [[ "$Branch" =~ ^(v)([1-9]\d*|0)(\.(([1-9]\d*)|0)){2}$ ]]; then
            echo "Matches"
            echo "::set-output name=test::prod"
          fi
      - name: Show variables
        run: |
          echo Branch: ${GITHUB_REF/refs\/tags\//}
          echo VALUE: ${{ needs.deployProd.outputs.output1 }}
          echo boolean: ${{ needs.deployProd.outputs.output1 == 'prod' }}
      - name: Deploy
        run: echo "Deploy Prod ${{ needs.deployProd.outputs.output1 }}"
        if: ${{ needs.deployProd.outputs.output1 == 'prod' }}

  deployUat:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Show variables
        run: |
          echo Branch: ${GITHUB_REF/refs\/tags\//}
          echo VALUE: ${{ needs.deployProd.outputs.output1 }}
          echo boolean: ${{ needs.deployProd.outputs.output1 != 'prod'}}
      - name: Deploy
        run: echo "Deploy UAT ${{needs.deployProd.outputs.output1}}"
        if: ${{ needs.deployProd.outputs.output1 != 'prod'}}
