name: deploy:prod

on:
  push:
    tags:
      - "**"
jobs:
  deployProd:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Check release
        # Directory name only
        uses: ./.github/actions/check-release
        with:
          release: ${GITHUB_REF/refs\/tags\//}
      - name: Show variables
        run: |
          echo "VALUE: $IS_PROD"
          echo "boolean: ${{ IS_PROD == 'true' }}"
      - name: Deploy
        run: echo "Deploy Prod ${{ IS_PROD }}"
        if: ${{ IS_PROD == 'true' }}

  deployUat:
    runs-on: ubuntu-latest
    needs: deployProd
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Check release
        # Directory name only
        uses: ./.github/actions/check-release
        with:
          release: ${GITHUB_REF/refs\/tags\//}
      - name: Show variables
        run: |
          echo "VALUE: $IS_PROD"
          echo "boolean: ${{ IS_PROD != 'true'}}"
      - name: Deploy
        run: echo "Deploy UAT ${{ IS_PROD }}"
        if: ${{ IS_PROD != 'true' }}
