name: deploy:prod

on:
  push:
    tags:
      - "**"
jobs:
  deployProd:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Deploy
        run: echo "Deploy Prod"
        if: $Branch =~ ^(v)([1-9]\d*|0)(\.(([1-9]\d*)|0)){2}$

  deployUat:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Deploy
        run: echo "Deploy UAT"
        if: ! $Branch =~ ^(v)([1-9]\d*|0)(\.(([1-9]\d*)|0)){2}$
