name: deploy:review
on:
  push:
jobs:
  deploy-web3-review:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Deploy contracts
        id: step1
        run: |
          VAR=true
          Branch=v0.1.2
          echo $Branch
          if [[ "$Branch" =~ ^(v)([1-9]\d*|0)(\.(([1-9]\d*)|0)){2}$ ]]; then
            echo "Matches"
            echo "::set-output name=test::$VAR"
          fi
      - name: Show variables
        run: |
          echo "VALUE: ${{needs.deploy-web3-review.outputs.output1}}"
          echo "boolean: ${{needs.deploy-web3-review.outputs.output1 == 'true'}}"
  build-amal-web-review:
    runs-on: ubuntu-latest
    needs: deploy-web3-review
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Build
        run: |
          echo "CONTRACT_ADDRESS=${{needs.deploy-web3-review.outputs.output1}}"
