name: deploy:review
on:
  push:
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.main.outputs.test }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Deploy contracts
        id: main
        run: |
          echo "::set-output name=test::1"
      - name: Run Project A
        if: steps.main.outputs.test == 1
        run: |
          echo Value ${{steps.main.outputs.test}}
          echo Boolean ${{steps.main.outputs.test == 1}}
  deploy-uat:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Build
        run: |
          echo Value "${{needs.deploy-prod.outputs.output1}}"
