name: deploy:prod

on:
  push:
    tags:
      - 0.0.2

jobs:
  # API
  static-check-api:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Test
        run: |
          echo Branch: ${GITHUB_REF/refs\/tags\//}
