name: deploy:prod

on:
  push:
    tags:
      - "**"
jobs:
  deployProd:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set variables
        id: step1
        run: |
          VAR=true
          Branch=${GITHUB_REF/refs\/tags\//}
          echo $Branch
          if [[ "$Branch" =~ ^(v)([1-9]\d*|0)(\.(([1-9]\d*)|0)){2}$ ]]; then
            echo "Matches"
            echo "::set-output name=test::$VAR"
            echo "IS_PROD=true" >> $GITHUB_ENV
          fi
      - name: Show variables
        run: |
          echo Branch: ${GITHUB_REF/refs\/tags\//}
          echo "VALUE: ${{ needs.deployProd.outputs.output1 }}"
          echo "boolean: ${{ needs.deployProd.outputs.output1 == 'true' }}"
          echo github env 1 $IS_PROD

      - name: Deploy
        run: echo "Deploy Prod ${{ needs.deployProd.outputs.output1 }}"
        if: ${{ needs.deployProd.outputs.output1 == 'true' }}

  deployUat:
    runs-on: ubuntu-latest
    needs: deployProd
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Show variables
        run: |
          echo Branch: ${GITHUB_REF/refs\/tags\//}
          echo "VALUE: ${{ needs.deployProd.outputs.output1 }}"
          echo "boolean: ${{ needs.deployProd.outputs.output1 != 'true'}}"
      - name: Deploy
        run: echo "Deploy UAT ${{needs.deployProd.outputs.output1}}"
        if: ${{ needs.deployProd.outputs.output1 != 'true'}}
