name: deploy:review
on:
  push:
jobs:
  deploy-web3-review:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.main.outputs.test }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Deploy contracts
        id: main
        run: |
          echo ""::set-output name=test::1"
      - name: Run Project A
        if: steps.main.outputs.test == 1
        run: |
          echo Value {{steps.main.outputs.test}}
          echo Boolean {{steps.main.outputs.test == 1}}
  # build-amal-web-review:
  #   runs-on: ubuntu-latest
  #   needs: deploy-web3-review
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v3
  #     - name: Build
  #       run: |
  #         cd packages/amal-web && cat .env
  #         echo “”
  #         echo “CONTRACT_ADDRESS=${{needs.deploy-web3-review.outputs.output1}}” > .env
  #         cat .env
