name: deploy:review
on:
  push:
jobs:
  deploy-web3-review:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Deploy contracts
        id: step1
        run: |
          VAR=true
          echo value of VAR is $VAR
          echo "::set-output name=test::$VAR"
  build-amal-web-review:
    runs-on: ubuntu-latest
    needs: deploy-web3-review
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Build
        run: |
          echo "CONTRACT_ADDRESS=${{needs.deploy-web3-review.outputs.output1}}"
