name: deploy:prod

on:
  workflow_dispatch:

jobs:
  deployProd:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set variables
        run: |
          BRANCH=v0.1.2
          if [[ "$BRANCH" =~ ^(v)([1-9]\d*|0)(\.(([1-9]\d*)|0)){2}$ ]]; then
            echo "Matches"
            echo "IS_PROD=true" >> $GITHUB_ENV
          else
            echo "IS_PROD=false" >> $GITHUB_ENV
          fi
      - name: Show variables
        if: env.IS_PROD == 'true'
        run: |
          echo "VALUE PROD: $IS_PROD"
          echo boolean env.IS_PROD == 'true'
      - name: Deploy
        if: env.IS_PROD == 'true'
        run: echo "Deploy Prod"

  deployUat:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set variables
        run: |
          BRANCH=v0.4.4
          if [[ "$BRANCH" =~ ^(v)([1-9]\d*|0)(\.(([1-9]\d*)|0)){2}$ ]]; then
            echo "Matches"
            echo "IS_PROD=true" >> $GITHUB_ENV
          else
            echo "IS_PROD=false" >> $GITHUB_ENV
          fi
      - name: Show variables
        run: |
          echo "VALUE PROD: $IS_PROD"
      - name: Deploy
        run: echo "Deploy UAT"
        if: env.IS_PROD == 'false'
