name: deploy:prod

on:
  push:
    tags:
      - "**"
jobs:
  deployProd:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set variables
        run: |
          BRANCH=${GITHUB_REF/refs\/tags\//}
          if [[ "$BRANCH" =~ ^(v)([1-9]\d*|0)(\.(([1-9]\d*)|0)){2}$ ]]; then
            echo "Matches"
            echo "IS_PROD=true" >> $GITHUB_ENV
          else
            echo "IS_PROD=false" >> $GITHUB_ENV
          fi
      - name: Show variables
        run: |
          echo "VALUE PROD: $IS_PROD"
      - name: Deploy
        run: echo "Deploy Prod"
        if: $IS_PROD == true

  deployUat:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set variables
        run: |
          BRANCH=${GITHUB_REF/refs\/tags\//}
          if [[ "$BRANCH" =~ ^(v)([1-9]\d*|0)(\.(([1-9]\d*)|0)){2}$ ]]; then
            echo "Matches"
            echo "IS_PROD=true" >> $GITHUB_ENV
          else
            echo "IS_PROD=false" >> $GITHUB_ENV
          fi
      - name: Show variables
        run: |
          echo "VALUE PROD: $IS_PROD"
      - name: Deploy
        run: echo "Deploy UAT"
        if: $IS_PROD == false
